import { z } from 'zod';

export const companySchema = z.object({
    nombre_compañia: z.string().optional(),
    nombre_legal_compañia: z.string().min(1, 'Legal name is required').optional(),
    fecha_de_constitucion: z.date().min(1, 'Incorporation date is required'),
    fecha_de_nacimiento: z.date().min(1, 'Date of establishment is required'),
    rfc: z.string().min(1, 'RFC is required'),
    curp: z.string().optional(),
    e_firma: z.string().optional(),
    no_sello: z.string().optional(),
    direccion: z.string().optional(),
    colonia: z.string().optional(),
    ciudad: z.string().optional(),
    estado: z.string().optional(),
    pais: z.string().optional(),
    codigo_postal: z.string().optional(),
    direccion_completa: z.string().optional(),
    comprobante_domicilio: z.any().optional(),
    correo: z.email('Invalid email address'),
    nombre_representante_legal: z.string().min(1, 'Legal representative name is required'),
    apellido_representante_legal: z.string().min(1, 'Legal representative surname is required'),
    numero_documento: z.string().optional(),
    tipo_documento: z.enum([
        'pasaporte',
        'ine',
        'licencia',
        'cartilla_militar'
    ]),
    rfc_entidad_legal: z.string().optional(),
    documento: z.file().optional(),
    poder: z.file().optional(),
    acta_constitutiva: z.file().optional(),
    csf:  z.file().optional(),
    contrato: z.file().optional(),
    kyc: z.file().optional(),
    manifestacion: z.any().optional(),
    firma: z.file().optional(),
    user_id: z.number().min(1, 'User ID is required'),
    origen: z.enum([
        'boost',
        'bitrus',
        'lite'
    ]),
    nacionalidad: z.string().optional(),
    moral_fisica: z.boolean('Type must be boolean').optional(),
    giro_mercantil: z.string().optional(),
    telefono: z.string().optional(),
    origen_recursos: z.string().optional(),
    destino_recursos: z.string().optional(),
    volumen_transaccional: z.number().optional(),
    operaciones_approximadas: z.string().optional(),
    clabe: z.number().optional(),
    wallet: z.string().optional(),
})

export const personSchema = z.object({
    fecha_de_nacimiento: z.date().min(1, 'Date of establishment is required'),
    rfc: z.string().min(1, 'RFC is required'),
    curp: z.string().optional(),
    e_firma: z.string().optional(),
    no_sello: z.string().optional(),
    direccion: z.string().optional(),
    colonia: z.string().optional(),
    ciudad: z.string().optional(),
    estado: z.string().optional(),
    pais: z.string().optional(),
    codigo_postal: z.string().optional(),
    direccion_completa: z.string().optional(),
    comprobante_domicilio: z.any().optional(),
    correo: z.email('Invalid email address'),
    nombre_representante_legal: z.string().min(1, 'Legal representative name is required'),
    apellido_representante_legal: z.string().min(1, 'Legal representative surname is required'),
    numero_documento: z.string().optional(),
    tipo_documento: z.enum([
        'pasaporte',
        'ine',
        'licencia',
        'cartilla_militar'
    ]),
    documento: z.file().optional(),
    csf:  z.file().optional(),
    contrato: z.file().optional(),
    kyc: z.file().optional(),
    manifestacion: z.file().optional(),
    firma: z.file().optional(),
    user_id: z.number().min(1, 'User ID is required'),
    origen: z.enum([
        'boost',
        'bitrus',
        'lite'
    ]),
    nacionalidad: z.string().optional(),
    moral_fisica: z.boolean('Type must be boolean').optional(),
    telefono: z.string().optional(),
    origen_recursos: z.string().optional(),
    destino_recursos: z.string().optional(),
    volumen_transaccional: z.number().optional(),
    operaciones_approximadas: z.string().optional(),
    clabe: z.number().optional(),
    wallet: z.string().optional(),
})
export type CompanyFormData = z.infer<typeof companySchema>;
export type PersonFormData = z.infer<typeof personSchema>;
