import { z } from 'zod';

export const companySchema = z.object({
    nombre_compañia: z.string().min(1, 'Company name is required'),
    nombre_legal_compañia: z.string().min(1, 'Legal name is required'),
    fecha_de_constitucion: z.date().min(1, 'Incorporation date is required'),
    fecha_de_nacimiento: z.date().min(1, 'Date of establishment is required'),
    rfc: z.string().min(1, 'RFC is required'),
    curp: z.string(),
    e_firma: z.string().optional(),
    no_sello: z.string().optional(),
    direccion: z.string().min(1, 'Address is required'),
    colonia: z.string(),
    ciudad: z.string(),
    estado: z.string(),
    pais: z.string(),
    codigo_postal: z.string(),
    direccion_completa: z.string().optional(),
    comprobante_domicilio: z.file(),
    correo: z.email('Invalid email address'),
    nombre_representante_legal: z.string().min(1, 'Legal representative name is required'),
    apellido_representante_legal: z.string().min(1, 'Legal representative surname is required'),
    numero_documento: z.number(),
    tipo_documento: z.enum([
        'pasaporte',
        'ine',
        'licencia',
        'cartilla_militar'
    ]),
    rfc_entidad_legal: z.string().min(1, 'Legal entity RFC is required'),
    documento: z.file(),
    poder: z.file(),
    acta_constitutiva: z.file(),
    csf:  z.file(),
    contrato: z.file().optional(),
    kyc: z.file().optional(),
    manifestacion: z.file().optional(),
    firma: z.file().optional(),
    user_id: z.string().min(1, 'User ID is required'),
    origen: z.enum([
        'boost',
        'bitrus',
        'lite'
    ]),
    nacionalidad: z.string().optional(),
    moral_fisica: z.boolean('Type must be boolean').optional(),
    giro_mercantil: z.string().min(1, 'Business activity is required'),
    telefono: z.string().optional(),
    origen_recursos: z.string().min(1, 'Source of funds is required'),
    destino_recursos: z.string().min(1, 'Destination of funds is required'),
    volumen_transaccional: z.number().min(1, 'Transaction volume is required'),
    operaciones_approximadas: z.number().optional(),
    clabe: z.number().min(18, 'CLABE must be at least 18 digits'),
    wallet: z.string().optional(),
})

export const personSchema = z.object({
    fecha_de_nacimiento: z.date().min(1, 'Date of establishment is required'),
    rfc: z.string().min(1, 'RFC is required'),
    curp: z.string().min(1, 'CURP is required'),
    e_firma: z.string().optional(),
    no_sello: z.string().optional(),
    direccion: z.string().min(1, 'Address is required'),
    colonia: z.string(),
    ciudad: z.string(),
    estado: z.string(),
    pais: z.string().min(1, 'Country is required'),
    codigo_postal: z.string(),
    direccion_completa: z.string().optional(),
    comprobante_domicilio: z.file(),
    correo: z.email('Invalid email address'),
    nombre_representante_legal: z.string().min(1, 'Legal representative name is required'),
    apellido_representante_legal: z.string().min(1, 'Legal representative surname is required'),
    numero_documento: z.number().min(1, 'Document number is required'),
    tipo_documento: z.enum([
        'pasaporte',
        'ine',
        'licencia',
        'cartilla_militar'
    ]),
    documento: z.file(),
    csf:  z.file(),
    contrato: z.file().optional(),
    kyc: z.file().optional(),
    manifestacion: z.file().optional(),
    firma: z.file().optional(),
    user_id: z.string().min(1, 'User ID is required'),
    origen: z.enum([
        'boost',
        'bitrus',
        'lite'
    ]),
    nacionalidad: z.string(),
    moral_fisica: z.boolean('Type must be boolean').optional(),
    telefono: z.string(),
    origen_recursos: z.string(),
    destino_recursos: z.string(),
    volumen_transaccional: z.number(),
    operaciones_approximadas: z.number(),
    clabe: z.number().optional(),
    wallet: z.string().optional(),
})
export type CompanyFormData = z.infer<typeof companySchema>;
export type PersonFormData = z.infer<typeof personSchema>;
